include: "/views/_autogenerated_views/connexions.view.lkml"
include: "/views/_autogenerated_views/events.view.lkml"

explore: interne {
  view_name: events

join: connexions {
  type: left_outer
  relationship: many_to_one
  sql_on: ${connexions.partner} = ${events.partner} ;;
}

}
